# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojitGameManager',
            fields=[
                ('gamemanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playit.GameManager')),
                ('test', models.TextField(default=b'test')),
            ],
            options={
                'abstract': False,
            },
            bases=('playit.gamemanager',),
        ),
    ]
