# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playit', '0003_auto_20170428_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiGameManager',
            fields=[
                ('gamemanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playit.GameManager')),
            ],
            options={
                'abstract': False,
            },
            bases=('playit.gamemanager',),
        ),
        migrations.CreateModel(
            name='EmojiQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playit.Question')),
                ('emoji_name', models.TextField()),
                ('face', models.ImageField(upload_to=b'')),
            ],
            options={
                'abstract': False,
            },
            bases=('playit.question',),
        ),
    ]
