# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('playit', '0004_emojigamemanager_emojiquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_manager',
        ),
        migrations.AddField(
            model_name='game',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
